import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync, existsSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { renderTenant, renderAgentInstructions } from '../src/provisioner/render.js';
import { installTerminalWorkspace } from '../remote-terminal/workspace.mjs';
import type { Tenant } from '../src/types.js';
test('terminal stays off until explicitly installed and survives later tenant instruction refreshes', t => {
  const dir = mkdtempSync(path.join(tmpdir(), 'terminal-awareness-')), previous = process.env.MOC_TENANTS_DIR;
  process.env.MOC_TENANTS_DIR = dir;
  t.after(() => { if (previous === undefined) delete process.env.MOC_TENANTS_DIR; else process.env.MOC_TENANTS_DIR = previous; rmSync(dir, { recursive: true, force: true }); });
  const tenant: Tenant = { id: 'canary-test', name: 'Canary', contact: {}, channel: 'whatsapp', gatewayPort: 29995, tier: 'container', createdAt: new Date().toISOString(), capabilities: {}, nudgeLog: [] };
  const fleet = { releaseChannel: 'latest' as const, image: 'test/image', nextPort: 1 };
  renderTenant(tenant, fleet);
  const home = path.join(dir, tenant.id), keyPath = path.join(home, '.remote-terminal-key');
  assert(!existsSync(keyPath));
  assert(!readFileSync(path.join(home, 'workspace/AGENTS.md'), 'utf8').includes('managed-remote-terminal'));
  installTerminalWorkspace(home, tenant.id);
  const key = readFileSync(keyPath, 'utf8');
  renderTenant(tenant, fleet); renderAgentInstructions(tenant);
  assert.equal(readFileSync(keyPath, 'utf8'), key);
  const agents = readFileSync(path.join(home, 'workspace/AGENTS.md'), 'utf8');
  assert.equal(agents.match(/managed-remote-terminal:start/g)?.length, 1);
  assert(!agents.includes(key.trim()));
  assert.match(agents, /remote-terminal\/session.mjs create/);
  assert.equal(statSync(path.join(home, 'workspace/remote-terminal/account.json')).mode & 0o777, 0o600);
  const config = JSON.parse(readFileSync(path.join(home, 'config/openclaw.json'), 'utf8'));
  assert.equal(config.plugins.load.paths.filter((p: string) => p.includes('/managed-remote-terminal/')).length, 1);
});
